title: "Megan Mielke"
author: "Blog Author"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
exxcerpt_separator: "\n\n\"
date_format: "%B %d, %Y"

# Layout

show_social: true         # show title description and social links in the footer
show_excerpts: true       # show acticle excerpts on the home page
show_frame: true          # adds a pink frame to the site
show_sidebar: false       # show a sidebar instead of the usual header

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}
  
external: 
  - {title: Mail, icon: envelope, url: "mailto:mmielke2@wisc.edu"}
  - {title: Github, icon: github, url: "https://mmielke2.github.io/"}
  - {title: LinkedIn, icon: linkedin, url: "www.linkedin.com/in/meganmielke"}
  
